// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neaslator.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Neaslator.Migrations
{
    [DbContext(typeof(NeaslatorDbContext))]
    [Migration("20260614073753_SeedSupportedLanguages")]
    partial class SeedSupportedLanguages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Neaslator.Domain.Entities.MenuPublishSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("MenuId")
                        .IsUnique()
                        .HasDatabaseName("uq_snapshot_menu");

                    b.ToTable("menu_publish_snapshots", (string)null);
                });

            modelBuilder.Entity("Neaslator.Domain.Entities.SupportedLanguage", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<short>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.HasKey("Code");

                    b.ToTable("supported_languages", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "en",
                            EnglishName = "English",
                            IsActive = true,
                            NativeName = "English",
                            SortOrder = (short)1
                        },
                        new
                        {
                            Code = "tr",
                            EnglishName = "Turkish",
                            IsActive = true,
                            NativeName = "Türkçe",
                            SortOrder = (short)2
                        },
                        new
                        {
                            Code = "de",
                            EnglishName = "German",
                            IsActive = true,
                            NativeName = "Deutsch",
                            SortOrder = (short)3
                        },
                        new
                        {
                            Code = "fr",
                            EnglishName = "French",
                            IsActive = true,
                            NativeName = "Français",
                            SortOrder = (short)4
                        },
                        new
                        {
                            Code = "es",
                            EnglishName = "Spanish",
                            IsActive = true,
                            NativeName = "Español",
                            SortOrder = (short)5
                        },
                        new
                        {
                            Code = "it",
                            EnglishName = "Italian",
                            IsActive = true,
                            NativeName = "Italiano",
                            SortOrder = (short)6
                        },
                        new
                        {
                            Code = "pt",
                            EnglishName = "Portuguese",
                            IsActive = true,
                            NativeName = "Português",
                            SortOrder = (short)7
                        },
                        new
                        {
                            Code = "nl",
                            EnglishName = "Dutch",
                            IsActive = true,
                            NativeName = "Nederlands",
                            SortOrder = (short)8
                        },
                        new
                        {
                            Code = "ru",
                            EnglishName = "Russian",
                            IsActive = true,
                            NativeName = "Русский",
                            SortOrder = (short)9
                        },
                        new
                        {
                            Code = "ar",
                            EnglishName = "Arabic",
                            IsActive = true,
                            NativeName = "العربية",
                            SortOrder = (short)10
                        },
                        new
                        {
                            Code = "zh",
                            EnglishName = "Chinese",
                            IsActive = true,
                            NativeName = "中文",
                            SortOrder = (short)11
                        },
                        new
                        {
                            Code = "ja",
                            EnglishName = "Japanese",
                            IsActive = true,
                            NativeName = "日本語",
                            SortOrder = (short)12
                        },
                        new
                        {
                            Code = "ko",
                            EnglishName = "Korean",
                            IsActive = true,
                            NativeName = "한국어",
                            SortOrder = (short)13
                        },
                        new
                        {
                            Code = "pl",
                            EnglishName = "Polish",
                            IsActive = true,
                            NativeName = "Polski",
                            SortOrder = (short)14
                        },
                        new
                        {
                            Code = "sv",
                            EnglishName = "Swedish",
                            IsActive = true,
                            NativeName = "Svenska",
                            SortOrder = (short)15
                        },
                        new
                        {
                            Code = "da",
                            EnglishName = "Danish",
                            IsActive = true,
                            NativeName = "Dansk",
                            SortOrder = (short)16
                        },
                        new
                        {
                            Code = "no",
                            EnglishName = "Norwegian",
                            IsActive = true,
                            NativeName = "Norsk",
                            SortOrder = (short)17
                        },
                        new
                        {
                            Code = "fi",
                            EnglishName = "Finnish",
                            IsActive = true,
                            NativeName = "Suomi",
                            SortOrder = (short)18
                        },
                        new
                        {
                            Code = "el",
                            EnglishName = "Greek",
                            IsActive = true,
                            NativeName = "Ελληνικά",
                            SortOrder = (short)19
                        },
                        new
                        {
                            Code = "cs",
                            EnglishName = "Czech",
                            IsActive = true,
                            NativeName = "Čeština",
                            SortOrder = (short)20
                        },
                        new
                        {
                            Code = "hu",
                            EnglishName = "Hungarian",
                            IsActive = true,
                            NativeName = "Magyar",
                            SortOrder = (short)21
                        },
                        new
                        {
                            Code = "ro",
                            EnglishName = "Romanian",
                            IsActive = true,
                            NativeName = "Română",
                            SortOrder = (short)22
                        },
                        new
                        {
                            Code = "bg",
                            EnglishName = "Bulgarian",
                            IsActive = true,
                            NativeName = "Български",
                            SortOrder = (short)23
                        },
                        new
                        {
                            Code = "uk",
                            EnglishName = "Ukrainian",
                            IsActive = true,
                            NativeName = "Українська",
                            SortOrder = (short)24
                        },
                        new
                        {
                            Code = "he",
                            EnglishName = "Hebrew",
                            IsActive = true,
                            NativeName = "עברית",
                            SortOrder = (short)25
                        },
                        new
                        {
                            Code = "th",
                            EnglishName = "Thai",
                            IsActive = true,
                            NativeName = "ไทย",
                            SortOrder = (short)26
                        },
                        new
                        {
                            Code = "vi",
                            EnglishName = "Vietnamese",
                            IsActive = true,
                            NativeName = "Tiếng Việt",
                            SortOrder = (short)27
                        },
                        new
                        {
                            Code = "id",
                            EnglishName = "Indonesian",
                            IsActive = true,
                            NativeName = "Bahasa Indonesia",
                            SortOrder = (short)28
                        },
                        new
                        {
                            Code = "ms",
                            EnglishName = "Malay",
                            IsActive = true,
                            NativeName = "Bahasa Melayu",
                            SortOrder = (short)29
                        },
                        new
                        {
                            Code = "hi",
                            EnglishName = "Hindi",
                            IsActive = true,
                            NativeName = "हिन्दी",
                            SortOrder = (short)30
                        });
                });

            modelBuilder.Entity("Neaslator.Domain.Entities.TranslationMemoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<float>("ConfidenceScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("HitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("NormalizedSourceText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<short>("ProviderTier")
                        .HasColumnType("smallint");

                    b.Property<long>("SourceHash")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceLanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TargetLanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ProviderTier", "UpdatedAt")
                        .HasDatabaseName("ix_gtm_quality_upgrade")
                        .HasFilter("\"ProviderTier\" > 0");

                    b.HasIndex("SourceHash", "TargetLanguageCode")
                        .HasDatabaseName("ix_gtm_lookup");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("SourceHash", "TargetLanguageCode"), new[] { "NormalizedSourceText", "TranslatedText", "ProviderTier", "ConfidenceScore" });

                    b.HasIndex("SourceHash", "SourceLanguageCode", "TargetLanguageCode")
                        .IsUnique()
                        .HasDatabaseName("uq_source_target");

                    b.ToTable("global_translation_memory", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
